// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfLQFEXLyKnkTQpsiJec4I9tokA-_mjJQ',
    appId: '1:44452293857:web:3bc2ec4e33b4ba817adba0',
    messagingSenderId: '44452293857',
    projectId: 'todo-pro-f2f46',
    authDomain: 'todo-pro-f2f46.firebaseapp.com',
    storageBucket: 'todo-pro-f2f46.firebasestorage.app',
    measurementId: 'G-E2LYJP9E4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAZPqkIcHIwmHf5sjoILENpcSIiZ8d3zg',
    appId: '1:44452293857:android:9084188982870f1d7adba0',
    messagingSenderId: '44452293857',
    projectId: 'todo-pro-f2f46',
    storageBucket: 'todo-pro-f2f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI7S-XMdR2THnDd8St7Fndz6s_bNFXEkw',
    appId: '1:44452293857:ios:fc9da78b09bde1577adba0',
    messagingSenderId: '44452293857',
    projectId: 'todo-pro-f2f46',
    storageBucket: 'todo-pro-f2f46.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI7S-XMdR2THnDd8St7Fndz6s_bNFXEkw',
    appId: '1:44452293857:ios:fc9da78b09bde1577adba0',
    messagingSenderId: '44452293857',
    projectId: 'todo-pro-f2f46',
    storageBucket: 'todo-pro-f2f46.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfLQFEXLyKnkTQpsiJec4I9tokA-_mjJQ',
    appId: '1:44452293857:web:286fc83d04a863027adba0',
    messagingSenderId: '44452293857',
    projectId: 'todo-pro-f2f46',
    authDomain: 'todo-pro-f2f46.firebaseapp.com',
    storageBucket: 'todo-pro-f2f46.firebasestorage.app',
    measurementId: 'G-5EVWT7LDQS',
  );
}
